name: Build Application
on:
    push:
        branches:
            - main



jobs:
    Build-Application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: runs setup-node
              uses: actions/setup-node@v4
              with:
                node-version: '23.x'
            - run: npm i -g bun
            - run: bun i --frozen-lockfile
            - run: bun run build --if-present 

        